In [2]:
"""Embedding: In NLP, word embedding is a representation of words in the form of a real-valued vector that encodes the meaning of the words such that the words that are closer in vector space are expected to be similar in meaning.
"""
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Embedding, Flatten, SimpleRNN
from keras.utils import pad_sequences
from keras.datasets import imdb
# (X_train, y_train), (X_test, y_test) = imdb.load_data()

In [3]:
import numpy as np
docs = [
    'nice man',
    'good boy',
    'beautiful woman',
    'pretty girl',
    'handsome boy',
    'idiot boy',
    'illminded girl'
    'wicked woman',
    'mad man',
    'notorious kid'
]

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='Sarang') #this token is for new words, any new word in test data would be assigned this.
tokenizer.fit_on_texts(docs)
len(tokenizer.word_index)

16

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 5,  3,  0],
       [ 6,  2,  0],
       [ 7,  4,  0],
       [ 8,  9,  0],
       [10,  2,  0],
       [11,  2,  0],
       [12, 13,  4],
       [14,  3,  0],
       [15, 16,  0]], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(17, output_dim=2, input_shape=(5,)))
model.add(SimpleRNN(5))
model.summary()
#it basically assigns a unique vector to each unique word, thus params are input_dim = 17(number of distinct words+1(for padding)) multiplied with output_dim=2,hence 34.]
#And then output_dim*number of nodes in RNN + node**2 + 1*number of nodes(bias)

C:\Users\q\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 5, 2)           │            34 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 5)              │            40 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 74 (296.00 B)

 Trainable params: 74 (296.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.compile('adam', 'accuracy')
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
[[[-0.02153987  0.00931843]
  [-0.00537895 -0.0285759 ]
  [-0.04218699 -0.01771186]]

 [[ 0.01762762 -0.03340973]
  [ 0.02194123 -0.00903683]
  [-0.04218699 -0.01771186]]

 [[-0.00709835 -0.03504146]
  [ 0.0060497  -0.00513537]
  [-0.04218699 -0.01771186]]

 [[-0.02328203  0.00656308]
  [ 0.03748411 -0.04755216]
  [-0.04218699 -0.01771186]]

 [[-0.02901099  0.00632465]
  [ 0.02194123 -0.00903683]
  [-0.04218699 -0.01771186]]

 [[ 0.03801954  0.03963126]
  [ 0.02194123 -0.00903683]
  [-0.04218699 -0.01771186]]

 [[-0.04072467  0.01107015]
  [-0.01083815  0.00970332]
  [ 0.0060497  -0.00513537]]

 [[-0.04058375 -0.03867049]
  [-0.00537895 -0.0285759 ]
  [-0.04218699 -0.01771186]]

 [[ 0.02490493 -0.04796921]
  [-0.02948937  0.00150939]
  [-0.04218699 -0.01771186]]]
